# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=20, unique=True)),
                ('academic_score', models.IntegerField(default=0)),
                ('social_score', models.IntegerField(default=0)),
                ('no_grads', models.IntegerField(default=0)),
                ('no_viper', models.IntegerField(default=0)),
                ('no_homework', models.IntegerField(default=0)),
                ('no_tennent', models.IntegerField(default=0)),
                ('no_drop', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
    ]
