# Generated by Django 2.0.3 on 2018-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_auto_20180325_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_drop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_grads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_homework',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_tennent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_viper',
            field=models.IntegerField(default=0),
        ),
    ]
