# Generated by Django 2.0.3 on 2018-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_auto_20180327_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='no_drop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_grads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_homework',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_tennent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_viper',
            field=models.IntegerField(default=0),
        ),
    ]
